site_name: Echo-Live 帮助文档

repo_name: sheep-realms/Echo-Live-Doc
repo_url: https://github.com/sheep-realms/Echo-Live-Doc
edit_uri: ""
# site_url: https://sheep-realms.github.io/Echo-Live-Doc/

theme:
  name: material
  language: zh
  # logo: image/logo.png
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: green
      accent: green
      scheme: default
      toggle:
        icon: material//weather-sunny
        name: 切换到深色模式
    - media: "(prefers-color-scheme: dark)"
      primary: green
      accent: green
      scheme: slate
      toggle:
        icon: material/weather-night
        name: 切换到浅色模式
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    # - header.autohide
    # - navigation.expand
    # - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  custom_dir: overrides

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - footnotes
  # - pymdownx.tabbed:
  #   alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# plugins:
#   - social:
#       cards_layout_options:
#         font_family: Noto Sans SC

extra_css:
  - style/common.css

copyright: Copyright &copy; Sheep-realms 和该文档的贡献者们
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sheep-realms
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/43881503

nav:
- 首页: 
  - 欢迎使用: index.md
  - 如何下载: main/download.md
  - 如何使用: main/how-to-use.md
  - 授权协议与声明: main/copyright.md
- 客制化:
  - 总览: custom/index.md
  - 配置: custom/config.md
  - 主题: custom/theme.md
  - 音效: custom/sound.md
  - 扩展: custom/extension.md
- 消息格式:
  - start.js: message/index.md
  - 基本格式: message/base.md
  - 启动参数: message/start-par.md
  - 文本样式: message/style.md
  - 停顿: message/pause.md
  - 模拟打字: message/typewrite.md
  - 多个文本段落: message/paragraph.md
- 开发文档:
  - Echo: dev/echo.md
  - 定制主题: dev/theme.md