site_name: Echo-Live 帮助文档

repo_name: sheep-realms/Echo-Live-Doc
repo_url: https://github.com/sheep-realms/Echo-Live-Doc
edit_uri: ""
# site_url: https://sheep-realms.github.io/Echo-Live-Doc/

theme:
  name: material
  language: zh
  # logo: image/logo.png
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: green
      accent: green
      scheme: default
      toggle:
        icon: material//weather-sunny
        name: 切换到深色模式
    - media: "(prefers-color-scheme: dark)"
      primary: green
      accent: green
      scheme: slate
      toggle:
        icon: material/weather-night
        name: 切换到浅色模式
  features:
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    # - header.autohide
    # - navigation.expand
    # - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  custom_dir: overrides

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - glightbox
  - search
#   - social:
#       cards_layout_options:
#         font_family: Noto Sans SC

extra_css:
  - style/common.css

copyright: Copyright &copy; Sheep-realms 和该文档的贡献者们
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sheep-realms
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/43881503
  analytics:
    provider: google
    property: G-2F1KW42J1Q

nav:
- 首页: 
  - 欢迎使用: index.md
  - 如何下载: main/download.md
  - 如何使用: main/how-to-use.md
  - 常见问题: main/faq.md
  - 安全须知: main/security.md
  - 无障碍使用指南: main/accessible.md
  - 授权协议与声明: main/copyright.md
  - 历史记录: main/history.md
- 客制化:
  - 总览: custom/index.md
  - 配置: custom/config.md
  - 主题: custom/theme.md
  - 音效: custom/sound.md
  - 扩展: custom/extension.md
  - 消息事件: custom/event.md
  - 语言 / Language: custom/language.md
- 消息格式:
  - start.js: message/index.md
  - 基本段落格式: message/base.md
  - 快速格式化代码: message/formatting-code.md
  - 启动参数: message/start-par.md
  - 文本样式: message/style.md
  - 停顿: message/pause.md
  - 模拟打字: message/typewrite.md
  - 事件: message/event.md
  - 自定义数据: message/data.md
  - 多个文本段落: message/paragraph.md
  - 消息队列: message/message-list.md
- 开发文档:
  - Echo: dev/echo.md
  - 定制主题: dev/theme.md
  - GitHub 分支: dev/branches.md
  - 本地化: dev/i18n.md
  - 配置文件数据版本历史: dev/config-data-version.md
  - 广播:
    - 概览: dev/broadcast/index.md
    - API 参数格式: dev/broadcast/api.md
    - API 文档:
      - dev/broadcast/api/close.md
      - dev/broadcast/api/echo_next.md
      - dev/broadcast/api/hello.md
      - dev/broadcast/api/message_data.md
      - dev/broadcast/api/page_hidden.md
      - dev/broadcast/api/page_visible.md
      - dev/broadcast/api/ping.md
      - dev/broadcast/api/set_theme.md
      - dev/broadcast/api/set_theme_style_url.md
      - dev/broadcast/api/websocket_close.md